version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"

    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=secret
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: